version: '3.3'

services:
   db:
     image: mysql:5.7
     restart: "no"
     environment:
       MYSQL_ROOT_PASSWORD: root

   dev:
     depends_on:
       - db
     image: rap-dev-data:latest
     volumes:
       - ~/.ssh:/home/rstudio/.ssh
     ports:
       - "8787:8787"
     restart: "no"
     environment:
       PASSWORD: password
