on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 18 * * 0' # run Sundays at 18

name: Publish RStudio Docker images

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_rstudio_base:
    name: Build rstudio image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: ./rstudio/.
          file: ./rstudio/Dockerfile
          tags: local/rstudio:latest
          push: false
          load: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: GITHUB_PAT=${{ github.token }}
          outputs: type=docker,dest=${{ runner.temp }}/myimage.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: myimage
          path: ${{ runner.temp }}/myimage.tar

  push_devs_to_registry:
    needs: build_rstudio_base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [ltmv-dev, smerte-dev, ablanor-dev, noric-dev, traume-dev]
    name: Push ${{ matrix.image }} image to docker hub
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: myimage
          path: ${{ runner.temp }}
      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/myimage.tar
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Prepare tags
        id: docker_meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=schedule,pattern=weekly
            type=schedule,pattern=main
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v7
        with:
          context: ./${{ matrix.image }}/.
          file: ./${{ matrix.image }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            GITHUB_PAT=${{ github.token }}
            BASE_IMAGE=local/rstudio:latest
