on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 20 * * 0' # run Sundays at 20

name: Publish base R Docker images

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_base_to_registry:
    strategy:
      fail-fast: false
      matrix:
        image:
          - {name: base-r, platforms: "linux/amd64,linux/arm64"}
          - {name: base-r-alpine, platforms: "linux/amd64,linux/arm64"}
          - {name: base-r-alpine-latex, platforms: "linux/amd64"}
          - {name: rstudio, platforms: "linux/amd64,linux/arm64"}
    name: Push ${{ matrix.image.name }} image to docker hub
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: ${{ matrix.image.platforms }}
      context: ./${{ matrix.image.name }}/.
      cache: true
      build-args: GITHUB_PAT=${{ github.token }}
      meta-images: rapporteket/${{ matrix.image.name }}
      meta-tags: |
        type=ref,event=branch
        type=schedule,pattern=weekly
        type=schedule,pattern=main
        type=semver,pattern={{major}}.{{minor}}.{{patch}}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
