on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Lint Dockerfiles

jobs:
  lint_dockerfiles:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: "*/Dockerfile"
