on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - 'base-r/**'
      - 'base-r-alpine/**'
      - 'rstudio/**'
      - '.github/workflows/multi-platform.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'base-r/**'
      - 'base-r-alpine/**'
      - 'rstudio/**'
      - '.github/workflows/multi-platform.yml'
  schedule:
    - cron: '0 18 * * 0' # run Sundays at 18

name: Publish Docker image, both arm and amd

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registries:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: base-r}
          - {name: base-r-alpine}
          - {name: rstudio}
    name: Push ${{ matrix.config.name }} image to docker hub
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      context: ./${{ matrix.config.name }}/.
      cache: true
      meta-images: rapporteket/${{ matrix.config.name }}
      meta-tags: |
        type=ref,event=branch
        type=schedule,pattern=weekly
        type=schedule,pattern=main
        type=semver,pattern={{major}}.{{minor}}.{{patch}}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
